use super::*;

pub(crate) fn parse_keycode(key: &str) -> Option<KeyCode> {
    match key.to_lowercase().as_str() {
        "a" => Some(KeyCode::KeyA),
        "b" => Some(KeyCode::KeyB),
        "c" => Some(KeyCode::KeyC),
        "d" => Some(KeyCode::KeyD),
        "e" => Some(KeyCode::KeyE),
        "f" => Some(KeyCode::KeyF),
        "g" => Some(KeyCode::KeyG),
        "h" => Some(KeyCode::KeyH),
        "i" => Some(KeyCode::KeyI),
        "j" => Some(KeyCode::KeyJ),
        "k" => Some(KeyCode::KeyK),
        "l" => Some(KeyCode::KeyL),
        "m" => Some(KeyCode::KeyM),
        "n" => Some(KeyCode::KeyN),
        "o" => Some(KeyCode::KeyO),
        "p" => Some(KeyCode::KeyP),
        "q" => Some(KeyCode::KeyQ),
        "r" => Some(KeyCode::KeyR),
        "s" => Some(KeyCode::KeyS),
        "t" => Some(KeyCode::KeyT),
        "u" => Some(KeyCode::KeyU),
        "v" => Some(KeyCode::KeyV),
        "w" => Some(KeyCode::KeyW),
        "x" => Some(KeyCode::KeyX),
        "y" => Some(KeyCode::KeyY),
        "z" => Some(KeyCode::KeyZ),
        "0" => Some(KeyCode::Digit0),
        "1" => Some(KeyCode::Digit1),
        "2" => Some(KeyCode::Digit2),
        "3" => Some(KeyCode::Digit3),
        "4" => Some(KeyCode::Digit4),
        "5" => Some(KeyCode::Digit5),
        "6" => Some(KeyCode::Digit6),
        "7" => Some(KeyCode::Digit7),
        "8" => Some(KeyCode::Digit8),
        "9" => Some(KeyCode::Digit9),
        "space" => Some(KeyCode::Space),
        "enter" | "return" => Some(KeyCode::Enter),
        "escape" | "esc" => Some(KeyCode::Escape),
        "tab" => Some(KeyCode::Tab),
        "backspace" => Some(KeyCode::Backspace),
        "left" | "arrowleft" => Some(KeyCode::ArrowLeft),
        "right" | "arrowright" => Some(KeyCode::ArrowRight),
        "up" | "arrowup" => Some(KeyCode::ArrowUp),
        "down" | "arrowdown" => Some(KeyCode::ArrowDown),
        "shift" | "leftshift" => Some(KeyCode::ShiftLeft),
        "ctrl" | "leftctrl" => Some(KeyCode::ControlLeft),
        "alt" | "leftalt" => Some(KeyCode::AltLeft),
        "f1" => Some(KeyCode::F1),
        "f2" => Some(KeyCode::F2),
        "f3" => Some(KeyCode::F3),
        "f4" => Some(KeyCode::F4),
        "f5" => Some(KeyCode::F5),
        "f6" => Some(KeyCode::F6),
        "f7" => Some(KeyCode::F7),
        "f8" => Some(KeyCode::F8),
        "f9" => Some(KeyCode::F9),
        "f10" => Some(KeyCode::F10),
        "f11" => Some(KeyCode::F11),
        "f12" => Some(KeyCode::F12),
        _ => None,
    }
}

pub(crate) fn parse_mouse_button(button: &str) -> Option<MouseButton> {
    match button.to_lowercase().as_str() {
        "left" => Some(MouseButton::Left),
        "right" => Some(MouseButton::Right),
        "middle" => Some(MouseButton::Middle),
        _ => None,
    }
}

pub(crate) fn parse_gamepad_button(button: &str) -> Option<GamepadButton> {
    match button.to_lowercase().as_str() {
        "south" | "a" | "cross" => Some(GamepadButton::South),
        "north" | "y" | "triangle" => Some(GamepadButton::North),
        "east" | "b" | "circle" => Some(GamepadButton::East),
        "west" | "x" | "square" => Some(GamepadButton::West),
        "left_trigger" | "lt" => Some(GamepadButton::LeftTrigger),
        "right_trigger" | "rt" => Some(GamepadButton::RightTrigger),
        "left_trigger2" | "lt2" => Some(GamepadButton::LeftTrigger2),
        "right_trigger2" | "rt2" => Some(GamepadButton::RightTrigger2),
        "select" | "back" => Some(GamepadButton::Select),
        "start" | "menu" => Some(GamepadButton::Start),
        "left_stick" | "ls" => Some(GamepadButton::LeftThumb),
        "right_stick" | "rs" => Some(GamepadButton::RightThumb),
        "dpad_up" => Some(GamepadButton::DPadUp),
        "dpad_down" => Some(GamepadButton::DPadDown),
        "dpad_left" => Some(GamepadButton::DPadLeft),
        "dpad_right" => Some(GamepadButton::DPadRight),
        _ => None,
    }
}
